// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdVzvT9WshDe0i-H5kPU_Hx2jf9m2bOvo',
    appId: '1:414684863254:web:7b4b30ca2a20087259ce37',
    messagingSenderId: '414684863254',
    projectId: 'arthub-39cf5',
    authDomain: 'arthub-39cf5.firebaseapp.com',
    storageBucket: 'arthub-39cf5.firebasestorage.app',
    measurementId: 'G-GP324BSKFB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0TMYHwBPqPxmgO3zXtRv0JMwe6Z4vF6c',
    appId: '1:414684863254:android:94e0609f15cf825d59ce37',
    messagingSenderId: '414684863254',
    projectId: 'arthub-39cf5',
    storageBucket: 'arthub-39cf5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3pT-iPOchpqoo4Ze7NnLlJcywvP9k4Z8',
    appId: '1:414684863254:ios:e52edeb2c292955159ce37',
    messagingSenderId: '414684863254',
    projectId: 'arthub-39cf5',
    storageBucket: 'arthub-39cf5.firebasestorage.app',
    iosBundleId: 'com.example.arthub',
  );
}
